"""shelter city relation

Revision ID: 6a206ab31581
Revises: 733be51c7227
Create Date: 2021-11-11 15:26:20.038297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a206ab31581'
down_revision = '733be51c7227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelter', sa.Column('city_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'shelter', 'city', ['city_id'], ['id'], ondelete='cascade')
    op.drop_column('shelter', 'city')
    op.drop_column('shelter', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelter', sa.Column('state', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('shelter', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shelter', type_='foreignkey')
    op.drop_column('shelter', 'city_id')
    # ### end Alembic commands ###
