"""shelter unique constraint user email unique not user_name

Revision ID: aa4e54542630
Revises: fdec0ce5dc8c
Create Date: 2021-11-05 14:45:57.886586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa4e54542630'
down_revision = 'fdec0ce5dc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.alter_column('user', 'city_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
