"""downgrade relationships

Revision ID: e94621cc3428
Revises: b70657b87f0d
Create Date: 2021-10-16 18:53:58.462846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94621cc3428'
down_revision = 'b70657b87f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_constraint('image_post_id_fkey', 'image', type_='foreignkey')
    op.drop_constraint('image_user_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'image', 'user', ['user_id'], ['id'])
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.drop_constraint('post_shelter_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post', 'shelter', ['shelter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_shelter_id_fkey', 'post', 'shelter', ['shelter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_user_id_fkey', 'image', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('image_post_id_fkey', 'image', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
