"""simplify rel

Revision ID: fdec0ce5dc8c
Revises: ecfc1ebc2989
Create Date: 2021-10-22 15:11:03.486016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdec0ce5dc8c'
down_revision = 'ecfc1ebc2989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
